// One-time seed data, extracted from the original site. Used by admin.html's 'Import starter projects' button to populate Firestore on first setup.
export const seedProjects = [
  { title: "SnakeBites", category: "Endless Game", description: "Clone game of Snake.io and worm.io for a client.", image: "sb.jpg", link: "", order: 0, featured: true },
  { title: "Survivor.io", category: "Arcade Style 2D Game", description: "Action-Play game where player has to kill zone of enemy zombies.", image: "sv.jpg", link: "", order: 1, featured: true },
  { title: "AirDodge", category: "2D Endless Plane Game", description: "Air Dodge: Missile Mayhem is an exhilarating 2D arcade-style game.", image: "ad.jpg", link: "", order: 2, featured: true },
  { title: "PathFinder", category: "Endless Running Game", description: "Pathfinder - Endless Runner UP Game a very Unique idea of playing endless game in Tunnel View.", image: "pf.jpg", link: "", order: 3, featured: true },
  { title: "Penggies", category: "Endless Falling Game", description: "Penggies - Endless Fall Game Player has to avoid obstacles while falling from sky.", image: "pg.jpg", link: "", order: 4, featured: true },
  { title: "WoobleMan-Escape Room", category: "Adventures Game", description: "Avoid Lights or AI Enemy otherwise you die, escape from them and pass through locks and doors and go to the end Door.", image: "wm.jpg", link: "", order: 5, featured: true },
  { title: "HexaSort - Prototype", category: "Adventure Puzzle Game", description: "Sort the Puzzle- merge all cubes and wins.", image: "hs.jpg", link: "", order: 6, featured: false },
  { title: "Pou - Prototype", category: "Hit and smash type game", description: "Fun game to hit and smash the pou.", image: "po.jpg", link: "", order: 7, featured: false },
  { title: "Alif Alphabet", category: "Educational Game Level based", description: "Educational Game Level based .", image: "1.jpg", link: "", order: 8, featured: false },
  { title: "Ban Ban Horror Game", category: "Horror Game", description: "Hide and Pass the Horror level without come into eyes of evil enemies.", image: "2.jpg", link: "", order: 9, featured: false },
  { title: "BigMatch 5 African Theme", category: "Match-3 Puzzle", description: "Candy Crush Clone in African Theme.", image: "3.jpg", link: "", order: 10, featured: false },
  { title: "Bills Crasher", category: "Casual Mobile Game", description: "Fruit Ninja Clone game.", image: "4.jpg", link: "", order: 11, featured: false },
  { title: "BlackJack", category: "Casino Game", description: "BlackJack Casino Game.", image: "5.jpg", link: "", order: 12, featured: false },
  { title: "Cash Drop", category: "Endless Arcade", description: "Collect Cash from sky and store in bank avoid bombs or needles try to collect Endless game.", image: "6.jpg", link: "", order: 13, featured: false },
  { title: "Easy To Earn", category: "Casual Mobile Game", description: "Easy to Earn is money making game, user has to play game or watch ads for getting income and can withdraw as well.", image: "7.jpg", link: "", order: 14, featured: false },
  { title: "FreeKick", category: "Casual Mobile Game", description: "Penalty 2d Free Kick game where Player has to goal as much as he can according to timer and according to kicks.", image: "8.jpg", link: "", order: 15, featured: false },
  { title: "FrogBites", category: "Casual Mobile Game", description: "Player has to eat baits bugs using frog Long Tongue.", image: "9.jpg", link: "", order: 16, featured: false },
  { title: "Pass the Ace - Multiplayer Game", category: "Card game Multiplaye!", description: "Card game Multiplayer.", image: "10.jpg", link: "", order: 17, featured: false },
  { title: "OldMaid CardDual Game", category: "Multiplayer Game", description: "Card Dual is multiplayer Game, it's idea from OLD game name as BlackPeter or OldMaid game.", image: "11.jpg", link: "", order: 18, featured: false },
  { title: "Idle Food Venture", category: "Idle / Simulation", description: "Idle Food resturant game, player has to serve food to customers.", image: "12.jpg", link: "", order: 19, featured: false },
  { title: "Pixel Odessy", category: "Casual Mobile Game", description: "2D game where player has to kill enemy or collect food to pass the level.", image: "13.jpg", link: "", order: 20, featured: false },
  { title: "Plinko Casino Game", category: "Casino Game", description: "Drop the ball and if its hit with 1x,2x,3x you will get money accordingly, Famouse game clone.", image: "14.jpg", link: "", order: 21, featured: false },
  { title: "Match 3d Puzzle Game", category: "Match-3 Puzzle", description: "Player has to collect same items from Surface and merge into 3 otherwise will fail to pass the level.", image: "15.jpg", link: "", order: 22, featured: false },
  { title: "DiceGame - Adventures", category: "Casino Game", description: "Game includes, Spin game, Casino Lottery game, Dixe game player has to pass and fun he can build or destroy buildings as well.", image: "16.jpg", link: "", order: 23, featured: false },
  { title: "Puzzle 2d - Pipe connection Game", category: "Puzzle Game", description: "Player has to solve the puzzle for pipe connection.", image: "17.jpg", link: "", order: 24, featured: false },
  { title: "Rabit Land - Prototype", category: "Simulation Game", description: "Player has to farm food and show on desk, Ai buyers come and grab and pay on counter player has to go to counter to collect money.", image: "18.jpg", link: "", order: 25, featured: false },
  { title: "Race of Road - Clone Game", category: "Racing Game", description: "Level base 2d game, player has to move or pass the level and upgrade vehicle as well.", image: "188.jpg", link: "", order: 26, featured: false },
  { title: "StickHero", category: "Endless Arcade", description: "Endless Stick hero game.", image: "19.jpg", link: "", order: 27, featured: false },
  { title: "Red Light Green Light", category: "Multiplayer Game", description: "Multiplayer Blockchain integerated game develop in unity.", image: "20.jpg", link: "", order: 28, featured: false },
  { title: "Sniper 3D", category: "2D Shooter", description: "Player has to kill animals using sniper weapon.", image: "21.jpg", link: "", order: 29, featured: false },
  { title: "StretchBlock", category: "Puzzle Game", description: "Puzzle Game, player has to add blocks to collect points Can be vertical side or horizental side destroy.", image: "22.jpg", link: "", order: 30, featured: false },
  { title: "Floppy Feet", category: "Endless Arcade", description: "Endless Ninja Jump game, player has to pass the wall and score high globally.", image: "23.jpg", link: "", order: 31, featured: false },
  { title: "Traffic Sign - Quiz Test", category: "Educational Quiz", description: "Quiz game for Traffic Sign- player will get all necessary questions related traffic test.", image: "24.jpg", link: "", order: 32, featured: false },
  { title: "ZobieLand - Mayhum", category: "Match-3 Puzzle", description: "Candy Crush clone game with Zombie Theme.", image: "27.jpg", link: "", order: 33, featured: false },
  { title: "VFX Shooter Game", category: "2D Shooter", description: "Kill and Shoot Fruites from Sky.", image: "26.jpg", link: "", order: 34, featured: false },
  { title: "Timeline - 2d Shooting", category: "2D Shooting game", description: "2d Arcade Shooting Game.", image: "25.jpg", link: "", order: 35, featured: false }
];
